INSERT INTO `lms_database`.`userdetails` (`Id`, `email`, `first_name`, `last_name`, `Password`, `contact_number`, `verified`, `creator_stamp`, `creator_user`) VALUES ('1', 'devangmranganth@gmail.com', 'ranganath', 'devangm', '@Reset1998', '7483247031', '0', '2020-08-10 01:00:01', 'ranganath');
INSERT INTO `lms_database`.`userdetails` (`Id`, `email`, `first_name`, `last_name`, `Password`, `contact_number`, `verified`, `creator_stamp`, `creator_user`) VALUES ('2', 'devangmranganth1@gmail.com', 'ramu', 'devangm', '@Reset1998', '7483247032', '0', '2020-08-10 02:00:01', 'ranganath');
INSERT INTO `lms_database`.`userdetails` (`Id`, `email`, `first_name`, `last_name`, `Password`, `contact_number`, `verified`, `creator_stamp`, `creator_user`) VALUES ('3', 'devangmranganth2@gmail.com', 'somu', 'devangm', '@Reset1998', '7483247033', '0', '2020-08-10 03:00:01', 'ranganath');
INSERT INTO `lms_database`.`userdetails` (`Id`, `email`, `first_name`, `last_name`, `Password`, `contact_number`, `verified`, `creator_stamp`, `creator_user`) VALUES ('4', 'devangmranganth3@gmail.com', 'rajesh', 'devangm', '@Reset1998', '7483247034', '0', '2020-08-10 04:00:01', 'ranganath');
INSERT INTO `lms_database`.`userdetails` (`Id`, `email`, `first_name`, `last_name`, `Password`, `contact_number`, `verified`, `creator_stamp`, `creator_user`) VALUES ('5', 'devangmranganth4@gmail.com', 'rakesh', 'devangm', '@Reset1998', '7483247035', '0', '2020-08-10 05:00:01', 'ranganath');
INSERT INTO `lms_database`.`userdetails` (`Id`, `email`, `first_name`, `last_name`, `Password`, `contact_number`, `verified`, `creator_stamp`, `creator_user`) VALUES ('6', 'devangmranganth5@gmail.com', 'lokesh', 'devangm', '@Reset1998', '7483247036', '0', '2020-08-10 06:00:01', 'ranganath');
INSERT INTO `lms_database`.`userdetails` (`Id`, `email`, `first_name`, `last_name`, `Password`, `contact_number`, `verified`, `creator_stamp`, `creator_user`) VALUES ('7', 'devangmranganth6@gmail.com', 'mahesh', 'devangm', '@Reset1998', '7483247037', '0', '2020-08-10 07:00:01', 'ranganath');
INSERT INTO `lms_database`.`userdetails` (`Id`, `email`, `first_name`, `last_name`, `Password`, `contact_number`, `verified`, `creator_stamp`, `creator_user`) VALUES ('8', 'devangmranganth7@gmail.com', 'ganesh', 'devangm', '@Reset1998', '7483247038', '0', '2020-08-10 08:00:01', 'ranganath');
INSERT INTO `lms_database`.`userdetails` (`Id`, `email`, `first_name`, `last_name`, `Password`, `contact_number`, `verified`, `creator_stamp`, `creator_user`) VALUES ('9', 'devangmranganth8@gmail.com', 'suresh', 'devangm', '@Reset1998', '7483247039', '0', '2020-08-10 09:00:01', 'ranganath');
INSERT INTO `lms_database`.`userdetails` (`Id`, `email`, `first_name`, `last_name`, `Password`, `contact_number`, `verified`, `creator_stamp`, `creator_user`) VALUES ('10', 'devangmranganth9@gmail.com', 'naresh', 'devangm', '@Reset1998', '7483247030', '0', '2020-08-10 10:00:01', 'ranganath');


INSERT INTO `lms_database`.`hired candidate` (`Id`, `First Name`, `Last Name`, `EmailId`, `Hired City`, `Hired Date`, `Mobile Number`, `Permanent Pincode`, `Communication Remark`, `Knowledge Remark`, `Creator Stamp`, `Creator User`) VALUES ('1', 'ranganath', 'devangm', 'devangmranganath@gmail.com', 'bangalore', '2020-08-11', '7483247031', '515231', 'good', 'good', '2020-08-10 01:00:01', 'ranganath');
INSERT INTO `lms_database`.`hired candidate` (`Id`, `First Name`, `Last Name`, `EmailId`, `Hired City`, `Hired Date`, `Mobile Number`, `Permanent Pincode`, `Communication Remark`, `Knowledge Remark`, `Creator Stamp`, `Creator User`) VALUES ('2', 'ramu', 'devangm', 'devangmranganath1@gmail.com', 'bangalore', '2020-08-11', '7483247032', '515231', 'good', 'good', '2020-08-10 02:00:01', 'ranganath');
INSERT INTO `lms_database`.`hired candidate` (`Id`, `First Name`, `Last Name`, `EmailId`, `Hired City`, `Hired Date`, `Mobile Number`, `Permanent Pincode`, `Communication Remark`, `Knowledge Remark`, `Creator Stamp`, `Creator User`) VALUES ('3', 'somu', 'devangm', 'devangmranganath2@gmail.com', 'bangalore', '2020-08-11', '7483247033', '515231', 'good', 'good', '2020-08-10 03:00:01', 'ranganath');
INSERT INTO `lms_database`.`hired candidate` (`Id`, `First Name`, `Last Name`, `EmailId`, `Hired City`, `Hired Date`, `Mobile Number`, `Permanent Pincode`, `Communication Remark`, `Knowledge Remark`, `Creator Stamp`, `Creator User`) VALUES ('4', 'rajesh', 'devangm', 'devangmranganath3@gmail.com', 'bangalore', '2020-08-11', '7483247034', '515231', 'good', 'good', '2020-08-10 04:00:01', 'ranganath');
INSERT INTO `lms_database`.`hired candidate` (`Id`, `First Name`, `Last Name`, `EmailId`, `Hired City`, `Hired Date`, `Mobile Number`, `Permanent Pincode`, `Communication Remark`, `Knowledge Remark`, `Creator Stamp`, `Creator User`) VALUES ('5', 'rakesh', 'devangm', 'devangmranganath4@gmail.com', 'bangalore', '2020-08-11', '7483247035', '515231', 'good', 'good', '2020-08-10 05:00:01', 'ranganath');
INSERT INTO `lms_database`.`hired candidate` (`Id`, `First Name`, `Last Name`, `EmailId`, `Hired City`, `Hired Date`, `Mobile Number`, `Permanent Pincode`, `Communication Remark`, `Knowledge Remark`, `Creator Stamp`, `Creator User`) VALUES ('6', 'lokesh', 'devangm', 'devangmranganath5@gmail.com', 'bangalore', '2020-08-11', '7483247036', '515231', 'good', 'good', '2020-08-10 06:00:01', 'ranganath');
INSERT INTO `lms_database`.`hired candidate` (`Id`, `First Name`, `Last Name`, `EmailId`, `Hired City`, `Hired Date`, `Mobile Number`, `Permanent Pincode`, `Communication Remark`, `Knowledge Remark`, `Creator Stamp`, `Creator User`) VALUES ('7', 'mahesh', 'devangm', 'devangmranganath6@gmail.com', 'bangalore', '2020-08-11', '7483247037', '515231', 'good', 'good', '2020-08-10 07:00:01', 'ranganath');
INSERT INTO `lms_database`.`hired candidate` (`Id`, `First Name`, `Last Name`, `EmailId`, `Hired City`, `Hired Date`, `Mobile Number`, `Permanent Pincode`, `Communication Remark`, `Knowledge Remark`, `Creator Stamp`, `Creator User`) VALUES ('8', 'ganesh', 'devangm', 'devangmranganath7@gmail.com', 'bangalore', '2020-08-11', '7483247038', '515231', 'good', 'good', '2020-08-10 08:00:01', 'ranganath');
INSERT INTO `lms_database`.`hired candidate` (`Id`, `First Name`, `Last Name`, `EmailId`, `Hired City`, `Hired Date`, `Mobile Number`, `Permanent Pincode`, `Communication Remark`, `Knowledge Remark`, `Creator Stamp`, `Creator User`) VALUES ('9', 'suresh', 'devangm', 'devangmranganath8@gmail.com', 'bangalore', '2020-08-11', '7483247039', '515231', 'good', 'good', '2020-08-10 09:00:01', 'ranganath');
INSERT INTO `lms_database`.`hired candidate` (`Id`, `First Name`, `Last Name`, `EmailId`, `Hired City`, `Hired Date`, `Mobile Number`, `Permanent Pincode`, `Communication Remark`, `Knowledge Remark`, `Creator Stamp`, `Creator User`) VALUES ('10', 'naresh', 'devangm', 'devangmranganath9@gmail.com', 'bangalore', '2020-08-11', '7483247030', '515231', 'good', 'good', '2020-08-10 10:00:01', 'ranganath');

INSERT INTO `lms_database`.`fellowship candidate` (`Id`, `First Name`, `Last Name`, `EmailId`, `Hired City`, `Degree`, `Hired Date`, `Mobile Number`, `Permanent Pincode`, `Communication Remark`, `Knowledge Remark`, `Creator Stamp`, `Creator User`, `Birth Date`, `Is Birth Date Verified`, `Parent Name`, `Parent Mobile Number`, `Local Address`, `Permanent Address`, `Joining Date`, `Bank Information`, `Educational Information`) VALUES ('1', 'ranganath', 'devangm', 'devangmranganath@gmail.com', 'bangalore', 'b.tech', '2020-03-07', '7483247031', '515231', 'good', 'good', '2020-08-11 07:57:00', 'ranganath', '1996-07-01', '0', 'ranganath', '7483247031', 'bangalore', 'gorantla', '2020-03-07', '62428433621', 'bachelor');
INSERT INTO `lms_database`.`fellowship candidate` (`Id`, `First Name`, `Last Name`, `EmailId`, `Hired City`, `Degree`, `Hired Date`, `Mobile Number`, `Permanent Pincode`, `Communication Remark`, `Knowledge Remark`, `Creator Stamp`, `Creator User`, `Birth Date`, `Is Birth Date Verified`, `Parent Name`, `Parent Mobile Number`, `Local Address`, `Permanent Address`, `Joining Date`, `Bank Information`, `Educational Information`) VALUES ('2', 'ramu', 'devangm', 'devangmranganath1@gmail.com', 'bangalore', 'b.tech', '2020-03-07', '7483247032', '515231', 'good', 'good', '2020-08-11 07:57:00', 'ranganath', '1996-07-02', '0', 'ranganath', '7483247032', 'bangalore', 'gorantla', '2020-03-07', '62428433622', 'bachelor');
INSERT INTO `lms_database`.`fellowship candidate` (`Id`, `First Name`, `Last Name`, `EmailId`, `Hired City`, `Degree`, `Hired Date`, `Mobile Number`, `Permanent Pincode`, `Communication Remark`, `Knowledge Remark`, `Creator Stamp`, `Creator User`, `Birth Date`, `Is Birth Date Verified`, `Parent Name`, `Parent Mobile Number`, `Local Address`, `Permanent Address`, `Joining Date`, `Bank Information`, `Educational Information`) VALUES ('3', 'somu', 'devangm', 'devangmranganath2@gmail.com', 'bangalore', 'b.tech', '2020-03-07', '74832470333', '515231', 'good', 'good', '2020-08-11 07:57:00', 'ranganath', '1996-07-03', '0', 'ranganath', '7483247033', 'bangalore', 'gorantla', '2020-03-07', '62428433623', 'bachelor');
INSERT INTO `lms_database`.`fellowship candidate` (`Id`, `First Name`, `Last Name`, `EmailId`, `Hired City`, `Degree`, `Hired Date`, `Mobile Number`, `Permanent Pincode`, `Communication Remark`, `Knowledge Remark`, `Creator Stamp`, `Creator User`, `Birth Date`, `Is Birth Date Verified`, `Parent Name`, `Parent Mobile Number`, `Local Address`, `Permanent Address`, `Joining Date`, `Bank Information`, `Educational Information`) VALUES ('4', 'rajesh', 'devangm', 'devangmranganath3@gmail.com', 'bangalore', 'b.tech', '2020-03-07', '7483247034', '515231', 'good', 'good', '2020-08-11 07:57:00', 'ranganath', '1996-07-04', '0', 'ranganath', '7483247034', 'bangalore', 'gorantla', '2020-03-07', '62428433624', 'bachelor');
INSERT INTO `lms_database`.`fellowship candidate` (`Id`, `First Name`, `Last Name`, `EmailId`, `Hired City`, `Degree`, `Hired Date`, `Mobile Number`, `Permanent Pincode`, `Communication Remark`, `Knowledge Remark`, `Creator Stamp`, `Creator User`, `Birth Date`, `Is Birth Date Verified`, `Parent Name`, `Parent Mobile Number`, `Local Address`, `Permanent Address`, `Joining Date`, `Bank Information`, `Educational Information`) VALUES ('5', 'rakesh', 'devangm', 'devangmranganath4@gmail.com', 'bangalore', 'b.tech', '2020-03-07', '7483247035', '515231', 'good', 'good', '2020-08-11 07:57:00', 'ranganath', '1996-07-05', '0', 'ranganath', '7483247035', 'bangalore', 'gorantla', '2020-03-07', '62428433625', 'bachelor');
INSERT INTO `lms_database`.`fellowship candidate` (`Id`, `First Name`, `Last Name`, `EmailId`, `Hired City`, `Degree`, `Hired Date`, `Mobile Number`, `Permanent Pincode`, `Communication Remark`, `Knowledge Remark`, `Creator Stamp`, `Creator User`, `Birth Date`, `Is Birth Date Verified`, `Parent Name`, `Parent Mobile Number`, `Local Address`, `Permanent Address`, `Joining Date`, `Bank Information`, `Educational Information`) VALUES ('6', 'lokesh', 'devangm', 'devangmranganath5@gmail.com', 'bangalore', 'b.tech', '2020-03-07', '7483247036', '515231', 'good', 'good', '2020-08-11 07:57:00', 'ranganath', '1996-07-06', '0', 'ranganath', '7483247036', 'bangalore', 'gorantla', '2020-03-07', '62428433626', 'bachelor');
INSERT INTO `lms_database`.`fellowship candidate` (`Id`, `First Name`, `Last Name`, `EmailId`, `Hired City`, `Degree`, `Hired Date`, `Mobile Number`, `Permanent Pincode`, `Communication Remark`, `Knowledge Remark`, `Creator Stamp`, `Creator User`, `Birth Date`, `Is Birth Date Verified`, `Parent Name`, `Parent Mobile Number`, `Local Address`, `Permanent Address`, `Joining Date`, `Bank Information`, `Educational Information`) VALUES ('7', 'mahesh', 'devangm', 'devangmranganath6@gmail.com', 'bangalore', 'b.tech', '2020-03-07', '7483247037', '515231', 'good', 'good', '2020-08-11 07:57:00', 'ranganath', '1996-07-07', '0', 'ranganath', '7483247037', 'bangalore', 'gorantla', '2020-03-07', '62428433627', 'bachelor');
INSERT INTO `lms_database`.`fellowship candidate` (`Id`, `First Name`, `Last Name`, `EmailId`, `Hired City`, `Degree`, `Hired Date`, `Mobile Number`, `Permanent Pincode`, `Communication Remark`, `Knowledge Remark`, `Creator Stamp`, `Creator User`, `Birth Date`, `Is Birth Date Verified`, `Parent Name`, `Parent Mobile Number`, `Local Address`, `Permanent Address`, `Joining Date`, `Bank Information`, `Educational Information`) VALUES ('8', 'ganesh', 'devangm', 'devangmranganath7@gmail.com', 'bangalore', 'b.tech', '2020-03-07', '7483247038', '515231', 'good', 'good', '2020-08-11 07:57:00', 'ranganath', '1996-07-08', '0', 'ranganath', '7483247038', 'bangalore', 'gorantla', '2020-03-07', '62428433628', 'bachelor');
INSERT INTO `lms_database`.`fellowship candidate` (`Id`, `First Name`, `Last Name`, `EmailId`, `Hired City`, `Degree`, `Hired Date`, `Mobile Number`, `Permanent Pincode`, `Communication Remark`, `Knowledge Remark`, `Creator Stamp`, `Creator User`, `Birth Date`, `Is Birth Date Verified`, `Parent Name`, `Parent Mobile Number`, `Local Address`, `Permanent Address`, `Joining Date`, `Bank Information`, `Educational Information`) VALUES ('9', 'suresh', 'devangm', 'devangmranganath8@gmail.com', 'bangalore', 'b.tech', '2020-03-07', '7483247039', '515231', 'good', 'good', '2020-08-11 07:57:00', 'ranganath', '1996-07-09', '0', 'ranganath', '7483247039', 'bangalore', 'gorantla', '2020-03-07', '62428433629', 'bachelor');
INSERT INTO `lms_database`.`fellowship candidate` (`Id`, `First Name`, `Last Name`, `EmailId`, `Hired City`, `Degree`, `Hired Date`, `Mobile Number`, `Permanent Pincode`, `Communication Remark`, `Knowledge Remark`, `Creator Stamp`, `Creator User`, `Birth Date`, `Is Birth Date Verified`, `Parent Name`, `Parent Mobile Number`, `Local Address`, `Permanent Address`, `Joining Date`, `Bank Information`, `Educational Information`) VALUES ('10', 'naresh', 'devangm', 'devangmranganath9@gmail.com', 'bangalore', 'b.tech', '2020-03-07', '7483247030', '515231', 'good', 'good', '2020-08-11 07:57:00', 'ranganath', '1996-07-10', '0', 'ranganath', '7483247030', 'bangalore', 'gorantla', '2020-03-07', '62428433620', 'bachelor');

INSERT INTO `lms_database`.`candidate bank details` (`Id`, `Candidate Id`, `Name`, `Account Number`, `Is Account Num Verified`, `ifsc code`, `is_ifsc_code_verified`, `pan_number`, `is_pan_number_verified`, `addhaar_num`, `is_addhaar_num_verified`, `creator_stamp`, `creator_user`) VALUES ('1', '1', 'ranganath', '62428433621', '1', 'sbin000220', '1', 'DQSPR4641P', '1', '563689985881', '1', '2020-08-11 8:18:00', 'ranganath');
INSERT INTO `lms_database`.`candidate bank details` (`Id`, `Candidate Id`, `Name`, `Account Number`, `Is Account Num Verified`, `ifsc code`, `is_ifsc_code_verified`, `pan_number`, `is_pan_number_verified`, `addhaar_num`, `is_addhaar_num_verified`, `creator_stamp`, `creator_user`) VALUES ('2', '2', 'ramu', '62428433622', '1', 'sbin000220', '1', 'DQSPR4642P', '1', '563689985882', '1', '2020-08-11 8:18:00', 'ranganath');
INSERT INTO `lms_database`.`candidate bank details` (`Id`, `Candidate Id`, `Name`, `Account Number`, `Is Account Num Verified`, `ifsc code`, `is_ifsc_code_verified`, `pan_number`, `is_pan_number_verified`, `addhaar_num`, `is_addhaar_num_verified`, `creator_stamp`, `creator_user`) VALUES ('3', '3', 'somu', '62428433623', '1', 'sbin000220', '1', 'DQSPR4643P', '1', '563689985883', '1', '2020-08-11 8:18:00', 'ranganath');
INSERT INTO `lms_database`.`candidate bank details` (`Id`, `Candidate Id`, `Name`, `Account Number`, `Is Account Num Verified`, `ifsc code`, `is_ifsc_code_verified`, `pan_number`, `is_pan_number_verified`, `addhaar_num`, `is_addhaar_num_verified`, `creator_stamp`, `creator_user`) VALUES ('4', '4', 'rajesh', '62428433624', '1', 'sbin000220', '1', 'DQSPR4644P', '1', '563689985884', '1', '2020-08-11 8:18:00', 'ranganath');
INSERT INTO `lms_database`.`candidate bank details` (`Id`, `Candidate Id`, `Name`, `Account Number`, `Is Account Num Verified`, `ifsc code`, `is_ifsc_code_verified`, `pan_number`, `is_pan_number_verified`, `addhaar_num`, `is_addhaar_num_verified`, `creator_stamp`, `creator_user`) VALUES ('5', '5', 'rakesh', '62428433625', '1', 'sbin000220', '1', 'DQSPR4645P', '1', '563689985885', '1', '2020-08-11 8:18:00', 'ranganath');
INSERT INTO `lms_database`.`candidate bank details` (`Id`, `Candidate Id`, `Name`, `Account Number`, `Is Account Num Verified`, `ifsc code`, `is_ifsc_code_verified`, `pan_number`, `is_pan_number_verified`, `addhaar_num`, `is_addhaar_num_verified`, `creator_stamp`, `creator_user`) VALUES ('6', '6', 'lokesh', '62428433626', '1', 'sbin000220', '1', 'DQSPR4646P', '1', '563689985886', '1', '2020-08-11 8:18:00', 'ranganath');
INSERT INTO `lms_database`.`candidate bank details` (`Id`, `Candidate Id`, `Name`, `Account Number`, `Is Account Num Verified`, `ifsc code`, `is_ifsc_code_verified`, `pan_number`, `is_pan_number_verified`, `addhaar_num`, `is_addhaar_num_verified`, `creator_stamp`, `creator_user`) VALUES ('7', '7', 'mahesh', '62428433627', '1', 'sbin000220', '1', 'DQSPR4647P', '1', '563689985887', '1', '2020-08-11 8:18:00', 'ranganath');
INSERT INTO `lms_database`.`candidate bank details` (`Id`, `Candidate Id`, `Name`, `Account Number`, `Is Account Num Verified`, `ifsc code`, `is_ifsc_code_verified`, `pan_number`, `is_pan_number_verified`, `addhaar_num`, `is_addhaar_num_verified`, `creator_stamp`, `creator_user`) VALUES ('8', '8', 'ganesh', '62428433628', '1', 'sbin000220', '1', 'DQSPR4648P', '1', '563689985888', '1', '2020-08-11 8:18:00', 'ranganath');
INSERT INTO `lms_database`.`candidate bank details` (`Id`, `Candidate Id`, `Name`, `Account Number`, `Is Account Num Verified`, `ifsc code`, `is_ifsc_code_verified`, `pan_number`, `is_pan_number_verified`, `addhaar_num`, `is_addhaar_num_verified`, `creator_stamp`, `creator_user`) VALUES ('9', '9', 'suresh', '62428433629', '1', 'sbin000220', '1', 'DQSPR4649P', '1', '563689985889', '1', '2020-08-11 8:18:00', 'ranganath');
INSERT INTO `lms_database`.`candidate bank details` (`Id`, `Candidate Id`, `Name`, `Account Number`, `Is Account Num Verified`, `ifsc code`, `is_ifsc_code_verified`, `pan_number`, `is_pan_number_verified`, `addhaar_num`, `is_addhaar_num_verified`, `creator_stamp`, `creator_user`) VALUES ('10', '10', 'naresh', '62428433620', '1', 'sbin000220', '1', 'DQSPR4640P', '1', '563689985880', '1', '2020-08-11 8:18:00', 'ranganath');


INSERT INTO `lms_database`.`candidate qualification` (`Id`, `candidate_id`, `degree_name`, `is_degree_name_verified`, `passing_year`, `is_passing_year_verified`, `aggr_per`, `final_year_per`, `is_final_year_per_verified`, `training_institute`, `is_training_institute_verified`, `training_duration_month`, `is_training_duration_month_verified`, `creator_stamp`, `creator_user`) VALUES ('1', '1', 'b.tech', '0', '2018', '0', '80', '85', '0', 'jspiders', '0', '6', '0', '2020-08-11 10:17:00', 'ranganath');
INSERT INTO `lms_database`.`candidate qualification` (`Id`, `candidate_id`, `degree_name`, `is_degree_name_verified`, `passing_year`, `is_passing_year_verified`, `aggr_per`, `final_year_per`, `is_final_year_per_verified`, `training_institute`, `is_training_institute_verified`, `training_duration_month`, `is_training_duration_month_verified`, `creator_stamp`, `creator_user`) VALUES ('2', '2', 'b.tech', '0', '2018', '0', '80', '85', '0', 'jspiders', '0', '6', '0', '2020-08-11 10:18:00', 'ranganath');
INSERT INTO `lms_database`.`candidate qualification` (`Id`, `candidate_id`, `degree_name`, `is_degree_name_verified`, `passing_year`, `is_passing_year_verified`, `aggr_per`, `final_year_per`, `is_final_year_per_verified`, `training_institute`, `is_training_institute_verified`, `training_duration_month`, `is_training_duration_month_verified`, `creator_stamp`, `creator_user`) VALUES ('3', '3', 'b.tech', '0', '2018', '0', '80', '85', '0', 'jspiders', '0', '6', '0', '2020-08-11 10:19:00', 'ranganath');
INSERT INTO `lms_database`.`candidate qualification` (`Id`, `candidate_id`, `degree_name`, `is_degree_name_verified`, `passing_year`, `is_passing_year_verified`, `aggr_per`, `final_year_per`, `is_final_year_per_verified`, `training_institute`, `is_training_institute_verified`, `training_duration_month`, `is_training_duration_month_verified`, `creator_stamp`, `creator_user`) VALUES ('4', '4', 'b.tech', '0', '2018', '0', '80', '85', '0', 'jspiders', '0', '6', '0', '2020-08-11 10:20:00', 'ranganath');
INSERT INTO `lms_database`.`candidate qualification` (`Id`, `candidate_id`, `degree_name`, `is_degree_name_verified`, `passing_year`, `is_passing_year_verified`, `aggr_per`, `final_year_per`, `is_final_year_per_verified`, `training_institute`, `is_training_institute_verified`, `training_duration_month`, `is_training_duration_month_verified`, `creator_stamp`, `creator_user`) VALUES ('5', '5', 'b.tech', '0', '2018', '0', '80', '85', '0', 'jspiders', '0', '6', '0', '2020-08-11 10:21:00', 'ranganath');
INSERT INTO `lms_database`.`candidate qualification` (`Id`, `candidate_id`, `degree_name`, `is_degree_name_verified`, `passing_year`, `is_passing_year_verified`, `aggr_per`, `final_year_per`, `is_final_year_per_verified`, `training_institute`, `is_training_institute_verified`, `training_duration_month`, `is_training_duration_month_verified`, `creator_stamp`, `creator_user`) VALUES ('6', '6', 'b.tech', '0', '2018', '0', '80', '85', '0', 'jspiders', '0', '6', '0', '2020-08-11 10:22:00', 'ranganath');
INSERT INTO `lms_database`.`candidate qualification` (`Id`, `candidate_id`, `degree_name`, `is_degree_name_verified`, `passing_year`, `is_passing_year_verified`, `aggr_per`, `final_year_per`, `is_final_year_per_verified`, `training_institute`, `is_training_institute_verified`, `training_duration_month`, `is_training_duration_month_verified`, `creator_stamp`, `creator_user`) VALUES ('7', '7', 'b.tech', '0', '2018', '0', '80', '85', '0', 'jspiders', '0', '6', '0', '2020-08-11 10:23:00', 'ranganath');
INSERT INTO `lms_database`.`candidate qualification` (`Id`, `candidate_id`, `degree_name`, `is_degree_name_verified`, `passing_year`, `is_passing_year_verified`, `aggr_per`, `final_year_per`, `is_final_year_per_verified`, `training_institute`, `is_training_institute_verified`, `training_duration_month`, `is_training_duration_month_verified`, `creator_stamp`, `creator_user`) VALUES ('8', '8', 'b.tech', '0', '2018', '0', '80', '85', '0', 'jspiders', '0', '6', '0', '2020-08-11 10:24:00', 'ranganath');
INSERT INTO `lms_database`.`candidate qualification` (`Id`, `candidate_id`, `degree_name`, `is_degree_name_verified`, `passing_year`, `is_passing_year_verified`, `aggr_per`, `final_year_per`, `is_final_year_per_verified`, `training_institute`, `is_training_institute_verified`, `training_duration_month`, `is_training_duration_month_verified`, `creator_stamp`, `creator_user`) VALUES ('9', '9', 'b.tech', '0', '2018', '0', '80', '85', '0', 'jspiders', '0', '6', '0', '2020-08-11 10:25:00', 'ranganath');
INSERT INTO `lms_database`.`candidate qualification` (`Id`, `candidate_id`, `degree_name`, `is_degree_name_verified`, `passing_year`, `is_passing_year_verified`, `aggr_per`, `final_year_per`, `is_final_year_per_verified`, `training_institute`, `is_training_institute_verified`, `training_duration_month`, `is_training_duration_month_verified`, `creator_stamp`, `creator_user`) VALUES ('10', '10', 'b.tech', '0', '2018', '0', '80', '85', '0', 'jspiders', '0', '6', '0', '2020-08-11 10:26:00', 'ranganath');


INSERT INTO `lms_database`.`candidate document` (`Id`, `candidate_id`, `doc_type`, `creator_stamp`, `creator_user`) VALUES ('1', '1', 'pdf', '2020-08-11 10:25:00', 'ranganath');
INSERT INTO `lms_database`.`candidate document` (`Id`, `candidate_id`, `doc_type`, `creator_stamp`, `creator_user`) VALUES ('2', '2', 'pdf', '2020-08-11 10:26:00', 'ranganath');
INSERT INTO `lms_database`.`candidate document` (`Id`, `candidate_id`, `doc_type`, `creator_stamp`, `creator_user`) VALUES ('3', '3', 'pdf', '2020-08-11 10:27:00', 'ranganath');
INSERT INTO `lms_database`.`candidate document` (`Id`, `candidate_id`, `doc_type`, `creator_stamp`, `creator_user`) VALUES ('4', '4', 'pdf', '2020-08-11 10:28:00', 'ranganath');
INSERT INTO `lms_database`.`candidate document` (`Id`, `candidate_id`, `doc_type`, `creator_stamp`, `creator_user`) VALUES ('5', '5', 'pdf', '2020-08-11 10:29:00', 'ranganath');
INSERT INTO `lms_database`.`candidate document` (`Id`, `candidate_id`, `doc_type`, `creator_stamp`, `creator_user`) VALUES ('6', '6', 'pdf', '2020-08-11 10:30:00', 'ranganath');
INSERT INTO `lms_database`.`candidate document` (`Id`, `candidate_id`, `doc_type`, `creator_stamp`, `creator_user`) VALUES ('7', '7', 'pdf', '2020-08-11 10:31:00', 'ranganath');
INSERT INTO `lms_database`.`candidate document` (`Id`, `candidate_id`, `doc_type`, `creator_stamp`, `creator_user`) VALUES ('8', '8', 'pdf', '2020-08-11 10:32:00', 'ranganath');
INSERT INTO `lms_database`.`candidate document` (`Id`, `candidate_id`, `doc_type`, `creator_stamp`, `creator_user`) VALUES ('9', '9', 'pdf', '2020-08-11 10:33:00', 'ranganath');
INSERT INTO `lms_database`.`candidate document` (`Id`, `candidate_id`, `doc_type`, `creator_stamp`, `creator_user`) VALUES ('10', '10', 'pdf', '2020-08-11 10:34:00', 'ranganath');


INSERT INTO `lms_database`.`company` (`Id`, `name`, `address`, `location`, `status`, `creator_stamp`, `creator_user`) VALUES ('1', 'thoughtworks', 'hyderabad', 'telangana', '0', '2020-08-11 10:30:00', 'ranganath');
INSERT INTO `lms_database`.`company` (`Id`, `name`, `address`, `location`, `status`, `creator_stamp`, `creator_user`) VALUES ('2', 'vinuculam', 'hyderabad', 'telangana', '0', '2020-08-11 10:30:00', 'ranganath');
INSERT INTO `lms_database`.`company` (`Id`, `name`, `address`, `location`, `status`, `creator_stamp`, `creator_user`) VALUES ('3', 'emphasis', 'bangalore', 'karnataka', '0', '2020-08-11 10:30:00', 'ranganath');
INSERT INTO `lms_database`.`company` (`Id`, `name`, `address`, `location`, `status`, `creator_stamp`, `creator_user`) VALUES ('4', 'facebook', 'mumbai', 'mahatastra', '0', '2020-08-11 10:30:00', 'ranganath');
INSERT INTO `lms_database`.`company` (`Id`, `name`, `address`, `location`, `status`, `creator_stamp`, `creator_user`) VALUES ('5', 'google', 'hyderabad', 'telangana', '0', '2020-08-11 10:30:00', 'ranganath');
INSERT INTO `lms_database`.`company` (`Id`, `name`, `address`, `location`, `status`, `creator_stamp`, `creator_user`) VALUES ('6', 'microsoft', 'bangalore', 'telangana', '0', '2020-08-11 10:30:00', 'ranganath');
INSERT INTO `lms_database`.`company` (`Id`, `name`, `address`, `location`, `status`, `creator_stamp`, `creator_user`) VALUES ('7', 'thoughtworks', 'hyderabad', 'telangana', '0', '2020-08-11 10:30:00', 'ranganath');
INSERT INTO `lms_database`.`company` (`Id`, `name`, `address`, `location`, `status`, `creator_stamp`, `creator_user`) VALUES ('8', 'wipro', 'hyderabad', 'telangana', '0', '2020-08-11 10:30:00', 'ranganath');
INSERT INTO `lms_database`.`company` (`Id`, `name`, `address`, `location`, `status`, `creator_stamp`, `creator_user`) VALUES ('9', 'tcs', 'bangalore', 'karnataka', '0', '2020-08-11 10:30:00', 'ranganath');
INSERT INTO `lms_database`.`company` (`Id`, `name`, `address`, `location`, `status`, `creator_stamp`, `creator_user`) VALUES ('10', 'thoughtworks', 'hyderabad', 'telangana', '0', '2020-08-11 10:30:00', 'ranganath');


INSERT INTO `lms_database`.`app_parameters` (`Id`, `key_type`, `key_value`, `key_text`, `cur_status`, `creator_stamp`, `creator_user`, `seq_num`) VALUES ('1', 'DOC_STATUS', 'PND', 'Pending', 'A', '2020-08-11 10:53:00', 'ranganath', '1');
INSERT INTO `lms_database`.`app_parameters` (`Id`, `key_type`, `key_value`, `key_text`, `cur_status`, `creator_stamp`, `creator_user`, `seq_num`) VALUES ('2', 'DOC_STATUS', 'RECEVD', 'Received', 'A', '2020-08-11 10:54:00', 'ranganath', '2');
INSERT INTO `lms_database`.`app_parameters` (`Id`, `key_type`, `key_value`, `key_text`, `cur_status`, `creator_stamp`, `creator_user`, `seq_num`) VALUES ('3', 'CUR_STATUS', 'ACTV', 'Active', 'A', '2020-08-11 10:54:00', 'ranganath', '1');
INSERT INTO `lms_database`.`app_parameters` (`Id`, `key_type`, `key_value`, `key_text`, `cur_status`, `creator_stamp`, `creator_user`, `seq_num`) VALUES ('4', 'DOC_STATUS', 'RECEVD', 'Received', 'A', '2020-08-11 10:55:00', 'ranganath', '2');
INSERT INTO `lms_database`.`app_parameters` (`Id`, `key_type`, `key_value`, `key_text`, `cur_status`, `creator_stamp`, `creator_user`, `seq_num`) VALUES ('5', 'CUR_STATUS', 'ACTV', 'Active', 'A', '2020-08-11 10:56:00', 'ranganath', '1');
INSERT INTO `lms_database`.`app_parameters` (`Id`, `key_type`, `key_value`, `key_text`, `cur_status`, `creator_stamp`, `creator_user`, `seq_num`) VALUES ('6', 'DOC_STATUS', 'RECEVD', 'Received', 'A', '2020-08-11 10:57:00', 'ranganath', '2');
INSERT INTO `lms_database`.`app_parameters` (`Id`, `key_type`, `key_value`, `key_text`, `cur_status`, `creator_stamp`, `creator_user`, `seq_num`) VALUES ('7', 'CUR_STATUS', 'IACTV', 'Inactive', 'A', '2020-08-11 10:58:00', 'ranganath', '1');
INSERT INTO `lms_database`.`app_parameters` (`Id`, `key_type`, `key_value`, `key_text`, `cur_status`, `creator_stamp`, `creator_user`, `seq_num`) VALUES ('8', 'DOC_STATUS', 'RECEVD', 'Received', 'A', '2020-08-11 10:59:00', 'ranganath', '2');
INSERT INTO `lms_database`.`app_parameters` (`Id`, `key_type`, `key_value`, `key_text`, `cur_status`, `creator_stamp`, `creator_user`, `seq_num`) VALUES ('9', 'CUR_STATUS', 'IACTV', 'Inactive', 'A', '2020-08-11 11:00:00', 'ranganath', '1');
INSERT INTO `lms_database`.`app_parameters` (`Id`, `key_type`, `key_value`, `key_text`, `cur_status`, `creator_stamp`, `creator_user`, `seq_num`) VALUES ('10', 'DOC_STATUS', 'RECEVD', 'Received', 'A', '2020-08-11 11:01:00', 'ranganath', '2');



INSERT INTO `lms_database`.`lab` (`Id`, `location`, `address`, `status`, `creator_stamp`, `creator_user`) VALUES ('1', 'bengalore', 'karnataka', '0', '2020-08-11 11:16:00', 'ranganath');
INSERT INTO `lms_database`.`lab` (`Id`, `location`, `address`, `status`, `creator_stamp`, `creator_user`) VALUES ('2', 'mumbai', 'maharastra', '0', '2020-08-11 11:16:00', 'ranganath');
INSERT INTO `lms_database`.`lab` (`Id`, `location`, `address`, `status`, `creator_stamp`, `creator_user`) VALUES ('3', 'pune', 'maharastra', '0', '2020-08-11 11:16:00', 'ranganath');
INSERT INTO `lms_database`.`lab` (`Id`, `location`, `address`, `status`, `creator_stamp`, `creator_user`) VALUES ('4', 'bengalore', 'karnataka', '0', '2020-08-11 11:16:00', 'ranganath');
INSERT INTO `lms_database`.`lab` (`Id`, `location`, `address`, `status`, `creator_stamp`, `creator_user`) VALUES ('5', 'chennai', 'tamilnadu', '0', '2020-08-11 11:16:00', 'ranganath');


INSERT INTO `lms_database`.`mentor` (`Id`, `name`, `mentor_type`, `lab_id`, `status`, `creator_stamp`, `creator_user`) VALUES ('1', 'pooja', 'ideation', '1', '0', '2020-08-11 11:13:00', 'ranganath');
INSERT INTO `lms_database`.`mentor` (`Id`, `name`, `mentor_type`, `lab_id`, `status`, `creator_stamp`, `creator_user`) VALUES ('2', 'venkat', 'lead', '2', '0', '2020-08-11 11:14:00', 'ranganath');
INSERT INTO `lms_database`.`mentor` (`Id`, `name`, `mentor_type`, `lab_id`, `status`, `creator_stamp`, `creator_user`) VALUES ('3', 'aishwarya', 'lead', '3', '0', '2020-08-11 11:15:00', 'ranganath');
INSERT INTO `lms_database`.`mentor` (`Id`, `name`, `mentor_type`, `lab_id`, `status`, `creator_stamp`, `creator_user`) VALUES ('4', 'vivek', 'lead', '4', '0', '2020-08-11 11:16:00', 'ranganath');
INSERT INTO `lms_database`.`mentor` (`Id`, `name`, `mentor_type`, `lab_id`, `status`, `creator_stamp`, `creator_user`) VALUES ('5', 'kalpesh', 'ideation', '5', '0', '2020-08-11 11:17:00', 'ranganath');


INSERT INTO `lms_database`.`mentor ideation map` (`Id`, `mentor_id`, `parent_id`, `status`, `creator_stamp`, `creator_user`) VALUES ('1', '1', '1', '0', '2020-08-11 11:40:00', 'ranganath');
INSERT INTO `lms_database`.`mentor ideation map` (`Id`, `mentor_id`, `parent_id`, `status`, `creator_stamp`, `creator_user`) VALUES ('2', '1', '2', '0', '2020-08-11 11:41:00', 'ranganath');
INSERT INTO `lms_database`.`mentor ideation map` (`Id`, `mentor_id`, `parent_id`, `status`, `creator_stamp`, `creator_user`) VALUES ('3', '1', '3', '0', '2020-08-11 11:42:00', 'ranganath');
INSERT INTO `lms_database`.`mentor ideation map` (`Id`, `mentor_id`, `parent_id`, `status`, `creator_stamp`, `creator_user`) VALUES ('4', '1', '4', '0', '2020-08-11 11:43:00', 'ranganath');
INSERT INTO `lms_database`.`mentor ideation map` (`Id`, `mentor_id`, `parent_id`, `status`, `creator_stamp`, `creator_user`) VALUES ('5', '1', '5', '0', '2020-08-11 11:44:00', 'ranganath');


INSERT INTO `lms_database`.`tech stack` (`Id`, `tech_name`, `cur_status`, `creator_stamp`, `creator_user`) VALUES ('1', 'java', 'A', '2020-08-11 11:46:00', 'ranganath');
INSERT INTO `lms_database`.`tech stack` (`Id`, `tech_name`, `cur_status`, `creator_stamp`, `creator_user`) VALUES ('2', 'php', 'A', '2020-08-11 11:47:00', 'ranganath');
INSERT INTO `lms_database`.`tech stack` (`Id`, `tech_name`, `cur_status`, `creator_stamp`, `creator_user`) VALUES ('3', 'python', 'A', '2020-08-11 11:48:00', 'ranganath');
INSERT INTO `lms_database`.`tech stack` (`Id`, `tech_name`, `cur_status`, `creator_stamp`, `creator_user`) VALUES ('4', 'java', 'A', '2020-08-11 11:49:00', 'ranganath');
INSERT INTO `lms_database`.`tech stack` (`Id`, `tech_name`, `cur_status`, `creator_stamp`, `creator_user`) VALUES ('5', 'mobile', 'A', '2020-08-11 11:50:00', 'ranganath');


INSERT INTO `lms_database`.`tech type` (`Id`, `type_name`, `cur_status`, `creator_stamp`, `creator_user`) VALUES ('1', 'full stack', 'A', '2020-08-11 11:53:00', 'ranganath');
INSERT INTO `lms_database`.`tech type` (`Id`, `type_name`, `cur_status`, `creator_stamp`, `creator_user`) VALUES ('2', 'back end', 'A', '2020-08-11 11:54:00', 'ranganath');
INSERT INTO `lms_database`.`tech type` (`Id`, `type_name`, `cur_status`, `creator_stamp`, `creator_user`) VALUES ('3', 'full stack', 'A', '2020-08-11 11:55:00', 'ranganath');
INSERT INTO `lms_database`.`tech type` (`Id`, `type_name`, `cur_status`, `creator_stamp`, `creator_user`) VALUES ('4', 'front end', 'A', '2020-08-11 11:56:00', 'ranganath');
INSERT INTO `lms_database`.`tech type` (`Id`, `type_name`, `cur_status`, `creator_stamp`, `creator_user`) VALUES ('5', 'full stack', 'A', '2020-08-11 11:57:00', 'ranganath');

INSERT INTO `lms_database`.`mentor tech stack` (`Id`, `mentor_id`, `tech_stack_id`, `datetime`, `status`, `creator_stamp`, `creator_user`) VALUES ('1', '1', '1', '2020-08-11 11:58:00', '0', '2020-08-11 11:58:00', 'ranganath');
INSERT INTO `lms_database`.`mentor tech stack` (`Id`, `mentor_id`, `tech_stack_id`, `datetime`, `status`, `creator_stamp`, `creator_user`) VALUES ('2', '2', '2', '2020-08-11 11:59:00', '0', '2020-08-11 11:58:00', 'ranganath');
INSERT INTO `lms_database`.`mentor tech stack` (`Id`, `mentor_id`, `tech_stack_id`, `datetime`, `status`, `creator_stamp`, `creator_user`) VALUES ('3', '3', '3', '2020-08-11 12:00:00', '0', '2020-08-11 11:59:00', 'ranganath');
INSERT INTO `lms_database`.`mentor tech stack` (`Id`, `mentor_id`, `tech_stack_id`, `datetime`, `status`, `creator_stamp`, `creator_user`) VALUES ('4', '4', '4', '2020-08-11 12:00:00', '0', '2020-08-11 12:00:00', 'ranganath');
INSERT INTO `lms_database`.`mentor tech stack` (`Id`, `mentor_id`, `tech_stack_id`, `datetime`, `status`, `creator_stamp`, `creator_user`) VALUES ('5', '5', '5', '2020-08-11 12:01:00', '0', '2020-08-11 12:01:00', 'ranganath');


INSERT INTO `lms_database`.`lab threshold` (`Id`, `lab_id`, `lab_capacity`, `status`, `creator_stamp`, `creator_user`) VALUES ('1', '1', '100', '0', '2020-08-11 12:04:00', 'ranganath');
INSERT INTO `lms_database`.`lab threshold` (`Id`, `lab_id`, `lab_capacity`, `status`, `creator_stamp`, `creator_user`) VALUES ('2', '2', '100', '0', '2020-08-11 12:05:00', 'ranganath');
INSERT INTO `lms_database`.`lab threshold` (`Id`, `lab_id`, `lab_capacity`, `status`, `creator_stamp`, `creator_user`) VALUES ('3', '3', '100', '0', '2020-08-11 12:06:00', 'ranganath');
INSERT INTO `lms_database`.`lab threshold` (`Id`, `lab_id`, `lab_capacity`, `status`, `creator_stamp`, `creator_user`) VALUES ('4', '4', '100', '0', '2020-08-11 12:07:00', 'ranganath');
INSERT INTO `lms_database`.`lab threshold` (`Id`, `lab_id`, `lab_capacity`, `status`, `creator_stamp`, `creator_user`) VALUES ('5', '5', '100', '0', '2020-08-11 12:08:00', 'ranganath');

INSERT INTO `lms_database`.`maker program` (`Id`, `tech_stack_id`, `tech_type_id`, `is_program_approved`, `creator_stamp`, `creator_user`) VALUES ('1', '1', '1', '0', '2020-08-11 12:11:00', 'ranganath');
INSERT INTO `lms_database`.`maker program` (`Id`, `tech_stack_id`, `tech_type_id`, `is_program_approved`, `creator_stamp`, `creator_user`) VALUES ('2', '2', '2', '0', '2020-08-11 12:12:00', 'ranganath');


INSERT INTO `lms_database`.`company requirement` (`Id`, `company_id`, `city`, `is_doc_verifrication`, `no_of_engg`, `status`, `creator_stamp`, `creator_user`, `tech_stack_id`, `tech_type_id`, `maker_program_id`, `lead_id`, `ideation_engg_id`, `buddy_engg_id`) VALUES ('1', '1', 'bengalore', '0', '1', '0', '2020-08-11 12:08:00', 'ranganath', '1', '1', '1', '1', '1', '1');
INSERT INTO `lms_database`.`company requirement` (`Id`, `company_id`, `city`, `is_doc_verifrication`, `no_of_engg`, `status`, `creator_stamp`, `creator_user`, `tech_stack_id`, `tech_type_id`, `maker_program_id`, `lead_id`, `ideation_engg_id`, `buddy_engg_id`) VALUES ('2', '2', 'mumbai', '0', '2', '0', '2020-08-11 12:09:00', 'ranganath', '1', '1', '1', '1', '1', '1');

INSERT INTO `lms_database`.`candidate stack assignment` (`Id`, `requirement_id`, `candidate_id`, `status`, `creator_stamp`, `creator_user`) VALUES ('1', '1', '1', '0', '2020-08-11 12:14:00', 'ranganath');
INSERT INTO `lms_database`.`candidate stack assignment` (`Id`, `requirement_id`, `candidate_id`, `status`, `creator_stamp`, `creator_user`) VALUES ('2', '2', '2', '0', '2020-08-11 12:15:00', 'ranganath');
